### ISSUE TITLE
way to add keywords

### ISSUE THREAD

**Issue by ParallaxCoder** [christophebe/julius-gpt#8]
hi, are there any plans to implement a keyword add feature to Julius-gpt articles? 

thanks for this incredible tool :)

**Comment by ParallaxCoder** [comment]
i forgot to mention. option to add FAQ section is another feature might be useful for many

**Comment by ParallaxCoder** [comment]
oh ok i noticed this feature can be achieved using template mode but can you add it to auto mode?

**Comment by christophebe** [comment]
Hi, 

Currently, this is one of the biggest problems with the tool. It's difficult to personalize the prompts. We need to work on it.  

Concerning the keywords : 

Until now, the keywords are suggested by the AI when building the post outline. 
See the following code : https://github.com/christophebe/julius-gpt/blob/main/src/lib/prompts.ts
If you are debugging, you will see the outline with the generated keywords in the console. 

Other possible solutions : 
- Custom prompts in order to specify the keywords you want to use
- Use external applications with their API : Semrush, yourtext.guru, ...
- ?


Concerning the FAQ in the auto mode, we can imagine more or less the same kind of solutions : 
-  add a custom prompt in addition to the audience & the intent. By this way, you can add a prompt like "Add a FAQ with the following questions ...." or "Generate a FAQ for the conclusion ..." 
- Give the possibility to replace the defaults prompts
- ? 

Thanks

**Comment by nikoandpiko** [comment]
Similar request involving prompt customizability. Ability to add certain aspects to the output e.g.
1. Include the 5 key takeaways from the article after the introduction
2. Have slug match h1 (separated by dashes)
3. Add unordered lists where applicable

I see there is some customizability with templates, but I think more documentation on it (incl. examples) would make it clearer on how to use it.

**Comment by ParallaxCoder** [comment]
@christophebe Thanks for the input. Yes, templates did the trick, but I agree with @nikoandpiko process could have been more straightforward. I had to fiddle around for some time to figure it out.

**Comment by christophebe** [comment]
Ok :-)

So, my conclusions are : 
- I will add more doc on templates and improve this mode. 
- Give the possibility to customize the default prompts for the auto mode. 

Thank you both
